// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOmSajau1X6TDhEsycwj4iilPx7HXsBXA',
    appId: '1:811759668685:android:5352b976aa49a9f2c60884',
    messagingSenderId: '811759668685',
    projectId: 'payday-mobile',
    storageBucket: 'payday-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLQbh5nn0HEjQTfz_p_7Ck9z1C9B89nA',
    appId: '1:811759668685:ios:a8e4df78f98b8669c60884',
    messagingSenderId: '811759668685',
    projectId: 'payday-mobile',
    storageBucket: 'payday-mobile.appspot.com',
    androidClientId: '811759668685-psorrtrvggth93kr5ooh1is1po3u01bl.apps.googleusercontent.com',
    iosClientId: '811759668685-to4ddl2aj1atapulknsi2m89f8afbft6.apps.googleusercontent.com',
    iosBundleId: 'com.solutions.gain.payDayMobile',
  );
}
