# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.0
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk --release

    # - name: Send APK via email
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     server_address: smtp.gmail.com
    #     server_port: 465
    #     username: perposetest7@gmail.com
    #     password: uutddotdfzuavoqy
    #     subject: "New APK Build"
    #     body: "Please find the attached APK file from the latest build."
    #     to: evan@gain.media
    #     from: perposetest7@gmail.com
    #     attachments: build/app/outputs/flutter-apk/app-release.apk



          
